package main

import (
	"database/sql"
	"fmt"
)

type seedEntry struct {
	CommonName     string
	ScientificName string
	Kingdom        string
	Phylum         string
	Class          string
	Order          string
	Family         string
}

func getSeedData() []seedEntry {
	return []seedEntry{
		{`Blue Whale`, `Balaenoptera musculus`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Balaenopteridae`},
		{`African Elephant`, `Loxodonta africana`, `Animalia`, `Chordata`, `Mammalia`, `Proboscidea`, `Elephantidae`},
		{`Asian Elephant`, `Elephas maximus`, `Animalia`, `Chordata`, `Mammalia`, `Proboscidea`, `Elephantidae`},
		{`Lion`, `Panthera leo`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Felidae`},
		{`Tiger`, `Panthera tigris`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Felidae`},
		{`Snow Leopard`, `Panthera uncia`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Felidae`},
		{`Cheetah`, `Acinonyx jubatus`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Felidae`},
		{`Jaguar`, `Panthera onca`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Felidae`},
		{`Domestic Cat`, `Felis catus`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Felidae`},
		{`Gray Wolf`, `Canis lupus`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Canidae`},
		{`Domestic Dog`, `Canis familiaris`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Canidae`},
		{`Red Fox`, `Vulpes vulpes`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Canidae`},
		{`Arctic Fox`, `Vulpes lagopus`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Canidae`},
		{`Brown Bear`, `Ursus arctos`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Ursidae`},
		{`Polar Bear`, `Ursus maritimus`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Ursidae`},
		{`Giant Panda`, `Ailuropoda melanoleuca`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Ursidae`},
		{`Raccoon`, `Procyon lotor`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Procyonidae`},
		{`Striped Skunk`, `Mephitis mephitis`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Mephitidae`},
		{`Wolverine`, `Gulo gulo`, `Animalia`, `Chordata`, `Mammalia`, `Carnivora`, `Mustelidae`},
		{`Hippopotamus`, `Hippopotamus amphibius`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Hippopotamidae`},
		{`Giraffe`, `Giraffa camelopardalis`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Giraffidae`},
		{`Bison`, `Bison bison`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Bovidae`},
		{`Domestic Cow`, `Bos taurus`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Bovidae`},
		{`Domestic Sheep`, `Ovis aries`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Bovidae`},
		{`Domestic Goat`, `Capra hircus`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Bovidae`},
		{`Dromedary Camel`, `Camelus dromedarius`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Camelidae`},
		{`Llama`, `Lama glama`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Camelidae`},
		{`White-tailed Deer`, `Odocoileus virginianus`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Cervidae`},
		{`Red Deer`, `Cervus elaphus`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Cervidae`},
		{`Moose`, `Alces alces`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Cervidae`},
		{`Reindeer`, `Rangifer tarandus`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Cervidae`},
		{`Domestic Pig`, `Sus scrofa domesticus`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Suidae`},
		{`Bottlenose Dolphin`, `Tursiops truncatus`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Delphinidae`},
		{`Orca`, `Orcinus orca`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Delphinidae`},
		{`Humpback Whale`, `Megaptera novaeangliae`, `Animalia`, `Chordata`, `Mammalia`, `Artiodactyla`, `Balaenopteridae`},
		{`Horse`, `Equus caballus`, `Animalia`, `Chordata`, `Mammalia`, `Perissodactyla`, `Equidae`},
		{`Plains Zebra`, `Equus quagga`, `Animalia`, `Chordata`, `Mammalia`, `Perissodactyla`, `Equidae`},
		{`White Rhinoceros`, `Ceratotherium simum`, `Animalia`, `Chordata`, `Mammalia`, `Perissodactyla`, `Rhinocerotidae`},
		{`Indian Rhinoceros`, `Rhinoceros unicornis`, `Animalia`, `Chordata`, `Mammalia`, `Perissodactyla`, `Rhinocerotidae`},
		{`Tapir`, `Tapirus terrestris`, `Animalia`, `Chordata`, `Mammalia`, `Perissodactyla`, `Tapiridae`},
		{`Human`, `Homo sapiens`, `Animalia`, `Chordata`, `Mammalia`, `Primates`, `Hominidae`},
		{`Chimpanzee`, `Pan troglodytes`, `Animalia`, `Chordata`, `Mammalia`, `Primates`, `Hominidae`},
		{`Western Gorilla`, `Gorilla gorilla`, `Animalia`, `Chordata`, `Mammalia`, `Primates`, `Hominidae`},
		{`Orangutan`, `Pongo pygmaeus`, `Animalia`, `Chordata`, `Mammalia`, `Primates`, `Hominidae`},
		{`Baboon`, `Papio anubis`, `Animalia`, `Chordata`, `Mammalia`, `Primates`, `Cercopithecidae`},
		{`Capuchin Monkey`, `Cebus capucinus`, `Animalia`, `Chordata`, `Mammalia`, `Primates`, `Cebidae`},
		{`Ring-tailed Lemur`, `Lemur catta`, `Animalia`, `Chordata`, `Mammalia`, `Primates`, `Lemuridae`},
		{`European Rabbit`, `Oryctolagus cuniculus`, `Animalia`, `Chordata`, `Mammalia`, `Lagomorpha`, `Leporidae`},
		{`Beaver`, `Castor canadensis`, `Animalia`, `Chordata`, `Mammalia`, `Rodentia`, `Castoridae`},
		{`House Mouse`, `Mus musculus`, `Animalia`, `Chordata`, `Mammalia`, `Rodentia`, `Muridae`},
		{`Brown Rat`, `Rattus norvegicus`, `Animalia`, `Chordata`, `Mammalia`, `Rodentia`, `Muridae`},
		{`Capybara`, `Hydrochoerus hydrochaeris`, `Animalia`, `Chordata`, `Mammalia`, `Rodentia`, `Caviidae`},
		{`Guinea Pig`, `Cavia porcellus`, `Animalia`, `Chordata`, `Mammalia`, `Rodentia`, `Caviidae`},
		{`Porcupine`, `Erethizon dorsatum`, `Animalia`, `Chordata`, `Mammalia`, `Rodentia`, `Erethizontidae`},
		{`Groundhog`, `Marmota monax`, `Animalia`, `Chordata`, `Mammalia`, `Rodentia`, `Sciuridae`},
		{`Eastern Gray Squirrel`, `Sciurus carolinensis`, `Animalia`, `Chordata`, `Mammalia`, `Rodentia`, `Sciuridae`},
		{`Red Kangaroo`, `Osphranter rufus`, `Animalia`, `Chordata`, `Mammalia`, `Diprotodontia`, `Macropodidae`},
		{`Koala`, `Phascolarctos cinereus`, `Animalia`, `Chordata`, `Mammalia`, `Diprotodontia`, `Phascolarctidae`},
		{`Platypus`, `Ornithorhynchus anatinus`, `Animalia`, `Chordata`, `Mammalia`, `Monotremata`, `Ornithorhynchidae`},
		{`Short-beaked Echidna`, `Tachyglossus aculeatus`, `Animalia`, `Chordata`, `Mammalia`, `Monotremata`, `Tachyglossidae`},
		{`Tasmanian Devil`, `Sarcophilus harrisii`, `Animalia`, `Chordata`, `Mammalia`, `Dasyuromorphia`, `Dasyuridae`},
		{`Virginia Opossum`, `Didelphis virginiana`, `Animalia`, `Chordata`, `Mammalia`, `Didelphimorphia`, `Didelphidae`},
		{`Bald Eagle`, `Haliaeetus leucocephalus`, `Animalia`, `Chordata`, `Aves`, `Accipitriformes`, `Accipitridae`},
		{`Golden Eagle`, `Aquila chrysaetos`, `Animalia`, `Chordata`, `Aves`, `Accipitriformes`, `Accipitridae`},
		{`Peregrine Falcon`, `Falco peregrinus`, `Animalia`, `Chordata`, `Aves`, `Falconiformes`, `Falconidae`},
		{`Red-tailed Hawk`, `Buteo jamaicensis`, `Animalia`, `Chordata`, `Aves`, `Accipitriformes`, `Accipitridae`},
		{`Osprey`, `Pandion haliaetus`, `Animalia`, `Chordata`, `Aves`, `Accipitriformes`, `Pandionidae`},
		{`Barn Owl`, `Tyto alba`, `Animalia`, `Chordata`, `Aves`, `Strigiformes`, `Tytonidae`},
		{`Great Horned Owl`, `Bubo virginianus`, `Animalia`, `Chordata`, `Aves`, `Strigiformes`, `Strigidae`},
		{`Snowy Owl`, `Bubo scandiacus`, `Animalia`, `Chordata`, `Aves`, `Strigiformes`, `Strigidae`},
		{`Rock Pigeon`, `Columba livia`, `Animalia`, `Chordata`, `Aves`, `Columbiformes`, `Columbidae`},
		{`Mourning Dove`, `Zenaida macroura`, `Animalia`, `Chordata`, `Aves`, `Columbiformes`, `Columbidae`},
		{`House Sparrow`, `Passer domesticus`, `Animalia`, `Chordata`, `Aves`, `Passeriformes`, `Passeridae`},
		{`American Robin`, `Turdus migratorius`, `Animalia`, `Chordata`, `Aves`, `Passeriformes`, `Turdidae`},
		{`European Starling`, `Sturnus vulgaris`, `Animalia`, `Chordata`, `Aves`, `Passeriformes`, `Sturnidae`},
		{`Northern Cardinal`, `Cardinalis cardinalis`, `Animalia`, `Chordata`, `Aves`, `Passeriformes`, `Cardinalidae`},
		{`Blue Jay`, `Cyanocitta cristata`, `Animalia`, `Chordata`, `Aves`, `Passeriformes`, `Corvidae`},
		{`American Crow`, `Corvus brachyrhynchos`, `Animalia`, `Chordata`, `Aves`, `Passeriformes`, `Corvidae`},
		{`Common Raven`, `Corvus corax`, `Animalia`, `Chordata`, `Aves`, `Passeriformes`, `Corvidae`},
		{`Magpie`, `Pica pica`, `Animalia`, `Chordata`, `Aves`, `Passeriformes`, `Corvidae`},
		{`Ruby-throated Hummingbird`, `Archilochus colubris`, `Animalia`, `Chordata`, `Aves`, `Apodiformes`, `Trochilidae`},
		{`Atlantic Puffin`, `Fratercula arctica`, `Animalia`, `Chordata`, `Aves`, `Charadriiformes`, `Alcidae`},
		{`Emperor Penguin`, `Aptenodytes forsteri`, `Animalia`, `Chordata`, `Aves`, `Sphenisciformes`, `Spheniscidae`},
		{`Ostrich`, `Struthio camelus`, `Animalia`, `Chordata`, `Aves`, `Struthioniformes`, `Struthionidae`},
		{`Emu`, `Dromaius novaehollandiae`, `Animalia`, `Chordata`, `Aves`, `Casuariiformes`, `Dromaiidae`},
		{`Greater Flamingo`, `Phoenicopterus roseus`, `Animalia`, `Chordata`, `Aves`, `Phoenicopteriformes`, `Phoenicopteridae`},
		{`Mute Swan`, `Cygnus olor`, `Animalia`, `Chordata`, `Aves`, `Anseriformes`, `Anatidae`},
		{`Mallard`, `Anas platyrhynchos`, `Animalia`, `Chordata`, `Aves`, `Anseriformes`, `Anatidae`},
		{`Canada Goose`, `Branta canadensis`, `Animalia`, `Chordata`, `Aves`, `Anseriformes`, `Anatidae`},
		{`Green Sea Turtle`, `Chelonia mydas`, `Animalia`, `Chordata`, `Reptilia`, `Testudines`, `Cheloniidae`},
		{`Leatherback Sea Turtle`, `Dermochelys coriacea`, `Animalia`, `Chordata`, `Reptilia`, `Testudines`, `Dermochelyidae`},
		{`Galapagos Tortoise`, `Chelonoidis nigra`, `Animalia`, `Chordata`, `Reptilia`, `Testudines`, `Testudinidae`},
		{`Komodo Dragon`, `Varanus komodoensis`, `Animalia`, `Chordata`, `Reptilia`, `Squamata`, `Varanidae`},
		{`Green Iguana`, `Iguana iguana`, `Animalia`, `Chordata`, `Reptilia`, `Squamata`, `Iguanidae`},
		{`King Cobra`, `Ophiophagus hannah`, `Animalia`, `Chordata`, `Reptilia`, `Squamata`, `Elapidae`},
		{`Reticulated Python`, `Malayopython reticulatus`, `Animalia`, `Chordata`, `Reptilia`, `Squamata`, `Pythonidae`},
		{`Boa Constrictor`, `Boa constrictor`, `Animalia`, `Chordata`, `Reptilia`, `Squamata`, `Boidae`},
		{`American Alligator`, `Alligator mississippiensis`, `Animalia`, `Chordata`, `Reptilia`, `Crocodilia`, `Alligatoridae`},
		{`Saltwater Crocodile`, `Crocodylus porosus`, `Animalia`, `Chordata`, `Reptilia`, `Crocodilia`, `Crocodylidae`},
		{`Nile Crocodile`, `Crocodylus niloticus`, `Animalia`, `Chordata`, `Reptilia`, `Crocodilia`, `Crocodylidae`},
		{`Bullfrog`, `Lithobates catesbeianus`, `Animalia`, `Chordata`, `Amphibia`, `Anura`, `Ranidae`},
		{`Red-eyed Tree Frog`, `Agalychnis callidryas`, `Animalia`, `Chordata`, `Amphibia`, `Anura`, `Phyllomedusidae`},
		{`Poison Dart Frog`, `Dendrobates tinctorius`, `Animalia`, `Chordata`, `Amphibia`, `Anura`, `Dendrobatidae`},
		{`Fire Salamander`, `Salamandra salamandra`, `Animalia`, `Chordata`, `Amphibia`, `Urodela`, `Salamandridae`},
		{`Axolotl`, `Ambystoma mexicanum`, `Animalia`, `Chordata`, `Amphibia`, `Urodela`, `Ambystomatidae`},
		{`Monarch Butterfly`, `Danaus plexippus`, `Animalia`, `Arthropoda`, `Insecta`, `Lepidoptera`, `Nymphalidae`},
		{`Honey Bee`, `Apis mellifera`, `Animalia`, `Arthropoda`, `Insecta`, `Hymenoptera`, `Apidae`},
		{`Seven-spotted Ladybug`, `Coccinella septempunctata`, `Animalia`, `Arthropoda`, `Insecta`, `Coleoptera`, `Coccinellidae`},
		{`Firefly`, `Lampyris noctiluca`, `Animalia`, `Arthropoda`, `Insecta`, `Coleoptera`, `Lampyridae`},
		{`Dragonfly`, `Anax junius`, `Animalia`, `Arthropoda`, `Insecta`, `Odonata`, `Aeshnidae`},
		{`House Fly`, `Musca domestica`, `Animalia`, `Arthropoda`, `Insecta`, `Diptera`, `Muscidae`},
		{`Mosquito`, `Aedes aegypti`, `Animalia`, `Arthropoda`, `Insecta`, `Diptera`, `Culicidae`},
		{`Praying Mantis`, `Mantis religiosa`, `Animalia`, `Arthropoda`, `Insecta`, `Mantodea`, `Mantidae`},
		{`Desert Locust`, `Schistocerca gregaria`, `Animalia`, `Arthropoda`, `Insecta`, `Orthoptera`, `Acrididae`},
		{`Tarantula`, `Theraphosa blondi`, `Animalia`, `Arthropoda`, `Arachnida`, `Araneae`, `Theraphosidae`},
		{`Black Widow Spider`, `Latrodectus mactans`, `Animalia`, `Arthropoda`, `Arachnida`, `Araneae`, `Theridiidae`},
		{`Emperor Scorpion`, `Pandinus imperator`, `Animalia`, `Arthropoda`, `Arachnida`, `Scorpiones`, `Scorpionidae`},
		{`American Lobster`, `Homarus americanus`, `Animalia`, `Arthropoda`, `Malacostraca`, `Decapoda`, `Nephropidae`},
		{`Blue Crab`, `Callinectes sapidus`, `Animalia`, `Arthropoda`, `Malacostraca`, `Decapoda`, `Portunidae`},
		{`Giant Squid`, `Architeuthis dux`, `Animalia`, `Mollusca`, `Cephalopoda`, `Oegopsida`, `Architeuthidae`},
		{`Common Octopus`, `Octopus vulgaris`, `Animalia`, `Mollusca`, `Cephalopoda`, `Octopoda`, `Octopodidae`},
		{`Garden Snail`, `Cornu aspersum`, `Animalia`, `Mollusca`, `Gastropoda`, `Stylommatophora`, `Helicidae`},
		{`Pacific Oyster`, `Crassostrea gigas`, `Animalia`, `Mollusca`, `Bivalvia`, `Ostreida`, `Ostreidae`},
		{`Common Starfish`, `Asterias rubens`, `Animalia`, `Echinodermata`, `Asteroidea`, `Forcipulatida`, `Asteriidae`},
		{`Sea Urchin`, `Strongylocentrotus purpuratus`, `Animalia`, `Echinodermata`, `Echinoidea`, `Stomopneustoida`, `Strongylocentrotidae`},
		{`Earthworm`, `Lumbricus terrestris`, `Animalia`, `Annelida`, `Clitellata`, `Crassiclitellata`, `Lumbricidae`},
		{`Great White Shark`, `Carcharodon carcharias`, `Animalia`, `Chordata`, `Chondrichthyes`, `Lamniformes`, `Lamnidae`},
		{`Whale Shark`, `Rhincodon typus`, `Animalia`, `Chordata`, `Chondrichthyes`, `Orectolobiformes`, `Rhincodontidae`},
		{`Manta Ray`, `Mobula birostris`, `Animalia`, `Chordata`, `Chondrichthyes`, `Myliobatiformes`, `Mobulidae`},
		{`Atlantic Salmon`, `Salmo salar`, `Animalia`, `Chordata`, `Actinopterygii`, `Salmoniformes`, `Salmonidae`},
		{`Goldfish`, `Carassius auratus`, `Animalia`, `Chordata`, `Actinopterygii`, `Cypriniformes`, `Cyprinidae`},
		{`Clownfish`, `Amphiprion ocellaris`, `Animalia`, `Chordata`, `Actinopterygii`, `Perciformes`, `Pomacentridae`},
		{`Atlantic Cod`, `Gadus morhua`, `Animalia`, `Chordata`, `Actinopterygii`, `Gadiformes`, `Gadidae`},
		{`Tuna`, `Thunnus thynnus`, `Animalia`, `Chordata`, `Actinopterygii`, `Scombriformes`, `Scombridae`},
		{`Anglerfish`, `Lophius piscatorius`, `Animalia`, `Chordata`, `Actinopterygii`, `Lophiiformes`, `Lophiidae`},
		{`Seahorse`, `Hippocampus kuda`, `Animalia`, `Chordata`, `Actinopterygii`, `Syngnathiformes`, `Syngnathidae`},
		{`Moon Jellyfish`, `Aurelia aurita`, `Animalia`, `Cnidaria`, `Scyphozoa`, `Semaeostomeae`, `Ulmaridae`},
		{`Sea Anemone`, `Metridium senile`, `Animalia`, `Cnidaria`, `Anthozoa`, `Actiniaria`, `Metridiidae`},
		{`Rose`, `Rosa gallica`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Rosales`, `Rosaceae`},
		{`Apple Tree`, `Malus domestica`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Rosales`, `Rosaceae`},
		{`Oak Tree`, `Quercus robur`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Fagales`, `Fagaceae`},
		{`Maple Tree`, `Acer saccharum`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Sapindales`, `Sapindaceae`},
		{`Elm Tree`, `Ulmus minor`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Rosales`, `Ulmaceae`},
		{`Willow Tree`, `Salix babylonica`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Malpighiales`, `Salicaceae`},
		{`Pine Tree`, `Pinus sylvestris`, `Plantae`, `Pinophyta`, `Pinopsida`, `Pinales`, `Pinaceae`},
		{`Spruce Tree`, `Picea abies`, `Plantae`, `Pinophyta`, `Pinopsida`, `Pinales`, `Pinaceae`},
		{`Redwood`, `Sequoia sempervirens`, `Plantae`, `Pinophyta`, `Pinopsida`, `Pinales`, `Cupressaceae`},
		{`Sunflower`, `Helianthus annuus`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Asterales`, `Asteraceae`},
		{`Daisy`, `Bellis perennis`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Asterales`, `Asteraceae`},
		{`Dandelion`, `Taraxacum officinale`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Asterales`, `Asteraceae`},
		{`Tulip`, `Tulipa gesneriana`, `Plantae`, `Magnoliophyta`, `Liliopsida`, `Liliales`, `Liliaceae`},
		{`Orchid`, `Phalaenopsis equestris`, `Plantae`, `Magnoliophyta`, `Liliopsida`, `Asparagales`, `Orchidaceae`},
		{`Rice`, `Oryza sativa`, `Plantae`, `Magnoliophyta`, `Liliopsida`, `Poales`, `Poaceae`},
		{`Wheat`, `Triticum aestivum`, `Plantae`, `Magnoliophyta`, `Liliopsida`, `Poales`, `Poaceae`},
		{`Corn`, `Zea mays`, `Plantae`, `Magnoliophyta`, `Liliopsida`, `Poales`, `Poaceae`},
		{`Bamboo`, `Bambusa vulgaris`, `Plantae`, `Magnoliophyta`, `Liliopsida`, `Poales`, `Poaceae`},
		{`Tomato`, `Solanum lycopersicum`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Solanales`, `Solanaceae`},
		{`Potato`, `Solanum tuberosum`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Solanales`, `Solanaceae`},
		{`Coffee`, `Coffea arabica`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Gentianales`, `Rubiaceae`},
		{`Cabbage`, `Brassica oleracea`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Brassicales`, `Brassicaceae`},
		{`Cacao`, `Theobroma cacao`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Malvales`, `Malvaceae`},
		{`Cotton`, `Gossypium hirsutum`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Malvales`, `Malvaceae`},
		{`Cucumber`, `Cucumis sativus`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Cucurbitales`, `Cucurbitaceae`},
		{`Pumpkin`, `Cucurbita pepo`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Cucurbitales`, `Cucurbitaceae`},
		{`Lemon`, `Citrus limon`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Sapindales`, `Rutaceae`},
		{`Orange`, `Citrus sinensis`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Sapindales`, `Rutaceae`},
		{`Grape`, `Vitis vinifera`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Vitales`, `Vitaceae`},
		{`Olive`, `Olea europaea`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Lamiales`, `Oleaceae`},
		{`Lavender`, `Lavandula angustifolia`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Lamiales`, `Lamiaceae`},
		{`Mint`, `Mentha spicata`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Lamiales`, `Lamiaceae`},
		{`Pea`, `Pisum sativum`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Fabales`, `Fabaceae`},
		{`Soybean`, `Glycine max`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Fabales`, `Fabaceae`},
		{`Cactus`, `Carnegiea gigantea`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Caryophyllales`, `Cactaceae`},
		{`Venus Flytrap`, `Dionaea muscipula`, `Plantae`, `Magnoliophyta`, `Magnoliopsida`, `Caryophyllales`, `Droseraceae`},
		{`Common Mushroom`, `Agaricus bisporus`, `Fungi`, `Basidiomycota`, `Agaricomycetes`, `Agaricales`, `Agaricaceae`},
		{`Shiitake`, `Lentinula edodes`, `Fungi`, `Basidiomycota`, `Agaricomycetes`, `Agaricales`, `Omphalotaceae`},
		{`Yeast`, `Saccharomyces cerevisiae`, `Fungi`, `Ascomycota`, `Saccharomycetes`, `Saccharomycetales`, `Saccharomycetaceae`},
		{`Fly Agaric`, `Amanita muscaria`, `Fungi`, `Basidiomycota`, `Agaricomycetes`, `Agaricales`, `Amanitaceae`},
		{`Morel`, `Morchella esculenta`, `Fungi`, `Ascomycota`, `Pezizomycetes`, `Pezizales`, `Morchellaceae`},
		{`Truffle`, `Tuber melanosporum`, `Fungi`, `Ascomycota`, `Pezizomycetes`, `Pezizales`, `Tuberaceae`},
	}
}

func SeedDatabase(database *sql.DB) error {
	seeds := getSeedData()
	tx, err := database.Begin()
	if err != nil { return fmt.Errorf("seed tx begin: %w", err) }
	stmt, err := tx.Prepare("INSERT OR IGNORE INTO species (common_name, scientific_name, kingdom, phylum, class, \"order\", family, last_synced) VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)")
	if err != nil { tx.Rollback(); return fmt.Errorf("seed prepare: %w", err) }
	defer stmt.Close()
	for i, s := range seeds {
		if _, err := stmt.Exec(s.CommonName, s.ScientificName, s.Kingdom, s.Phylum, s.Class, s.Order, s.Family); err != nil {
			tx.Rollback()
			return fmt.Errorf("seed row %d (%s): %w", i, s.ScientificName, err)
		}
	}
	return tx.Commit()
}

