// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchAndSaveFromAPI(arg1) {
  return window['go']['main']['App']['FetchAndSaveFromAPI'](arg1);
}

export function GetSpeciesByID(arg1) {
  return window['go']['main']['App']['GetSpeciesByID'](arg1);
}

export function SearchSpecies(arg1) {
  return window['go']['main']['App']['SearchSpecies'](arg1);
}

export function SyncSpecies(arg1) {
  return window['go']['main']['App']['SyncSpecies'](arg1);
}
