// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchAndSaveFromAPI(arg1:string):Promise<main.Species>;

export function GetSpeciesByID(arg1:number):Promise<main.Species>;

export function SearchSpecies(arg1:string):Promise<Array<main.Species>>;

export function SyncSpecies(arg1:string):Promise<main.Species>;
